services:
  attacker:
    image: attacker_image
    container_name: attacker
    volumes:
        - ./attacker:/src
    networks:
      lab_net:
        ipv4_address: 10.0.0.10
    tty: true
    cap_add:
        - ALL

  attacker_server:
    image: server_image
    container_name: attacker_server
    volumes:
        - ./attacker_server:/src
    networks:
      lab_net:
        ipv4_address: 10.0.0.20
    tty: true
    cap_add:
        - ALL

  original_server:
    image: server_image
    container_name: original_server
    volumes:
        - ./original_server:/src
    networks:
      lab_net:
        ipv4_address: 10.0.0.30
    tty: true
    cap_add:
        - ALL

  recursive_ns:
    image: ns_image
    container_name: recursive_ns
    ports:
      - "5301:53/udp"
      - "5302:12345/udp"
    networks:
      lab_net:
        ipv4_address: 10.0.0.40
    volumes:
        - ./recursive_ns:/etc/bind
    tty: true
    cap_add:
        - ALL

  tld_ns:
    image: ns_image
    container_name: tld_ns
    volumes:
        - ./tld_ns:/etc/bind
    ports:
      - "5303:53/tcp"
      - "5303:53/udp"
    networks:
      lab_net:
        ipv4_address: 10.0.0.50
    tty: true
    cap_add:
        - ALL

  victim:
    image: victim_image
    container_name: victim
    networks:
      lab_net:
        ipv4_address: 10.0.0.60
    tty: true
    cap_add:
        - ALL
    dns:
      - 10.0.0.40

  attacker_ns:
    image: ns_image
    container_name: attacker_ns
    volumes:
        - ./attacker_ns:/etc/bind
    ports:
      - "5304:53/udp"
      - "5304:53/tcp"
    networks:
      lab_net:
        ipv4_address: 10.0.0.70
    tty: true
    cap_add:
        - ALL
  google_ns:
    image: ns_image
    container_name: google_ns
    volumes:
        - ./google_ns:/etc/bind
    ports:
      - "5305:53/udp"
      - "5305:53/tcp"
    networks:
      lab_net:
        ipv4_address: 10.0.0.80
    tty: true
    cap_add:
        - ALL

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
